### ISSUE TITLE
Madhesia e historise shume e madhe

### ISSUE THREAD

**Issue by flakron** [kujtimiihoxha/gk#3]
Maspari te lumshin durt per ket tool.

Tash ne teme:
Mire ish kan me ba squash 1 pjese te historise (momentalisht git clone osht ka download 170mb). Nese ish ba squash kjo histori kish mujt me u zvoglu drastikisht (nen 1mb), diqka qe e kish zvoglu kohen edhe hapesiren qe e zen ky repo.

**Comment by kujtimiihoxha** [comment]
Faleminderit shum @flakron  nuk e paskam vrejt po shum osht rrit commit history, besoj qe tash osht ne rregull.
